name: practice1 workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Starting build process"

      - name: Build Complete
        run: echo "Build complete"
