name: Secret Demo

on: push

jobs:
  show-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Use secret
        run: echo "The secret value length check passed"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET_MESSAGE }}
